name: Timetree Exporter

on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 * * * *'  # every hour
  workflow_dispatch:

jobs:
  export-calendar:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.x

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Set environment variables
        run: |
          echo "DROPBOX_CLIENT_ID=${{ secrets.DROPBOX_CLIENT_ID }}" >> $GITHUB_ENV
          echo "DROPBOX_CLIENT_SECRET=${{ secrets.DROPBOX_CLIENT_SECRET }}" >> $GITHUB_ENV
          echo "DROPBOX_REFRESH_TOKEN=${{ secrets.DROPBOX_REFRESH_TOKEN }}" >> $GITHUB_ENV
          echo "TIMETREE_EMAIL=${{ secrets.TIMETREE_EMAIL }}" >> $GITHUB_ENV
          echo "TIMETREE_PASSWORD=${{ secrets.TIMETREE_PASSWORD }}" >> $GITHUB_ENV

      - name: Run the Timetree Exporter
        run: |
          python -m timetree_exporter
