name: TimeTree Exporter

on:
  schedule:
    - cron: "0 0,12 * * *"  # At midnight and noon UTC
  # Optionally trigger on push or pull request (uncomment if needed)
  # push:
  #   branches:
  #     - main  # or master depending on your branch name
  # pull_request:
  #   branches:
  #     - main

jobs:
  timetree_export:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the repository code
      - name: Check out repository
        uses: actions/checkout@v3

      # Step 2: Set up Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.8'  # Specify the Python version (e.g., 3.8 or 3.9)

      # Step 3: Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r timetree-exporter/requirements.txt

      # Step 4: Run the script
      - name: Run TimeTree Exporter
        env:
          TIMETREE_EMAIL: ${{ secrets.TIMETREE_EMAIL }}
          TIMETREE_PASSWORD: ${{ secrets.TIMETREE_PASSWORD }}
          DROPBOX_TOKEN: ${{ secrets.DROPBOX_TOKEN }}
        run: |
          python -m timetree_exporter
